export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const API_ERRORED = "API_ERRORED";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
export const RESET_INFORMATION_MESSAGE = "RESET_INFORMATION_MESSAGE";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";